services:
  yandex-spotify-connect:
    image: ghcr.io/badkiko/yandex-spotify-connect:latest
    build: .
    container_name: yandex_spotify_connect
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./cache:/app/cache
      - ./config.yaml:/app/config.yaml
